name: Behave tests in Docker

on:
  schedule:
    - cron: "30 9 * * 2,5"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.9

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install behave
        run: pip install behave

      - name: Install selenium
        run: pip install selenium
      
      - name: Install Webdriver Manager
        run: pip install webdriver_manager

      - name: Install Chromedriver
        run: |
          cd drivers
          export CHROME_VERSION=$(google-chrome-stable --version | grep -oP 'Google Chrome \K\w+')
          wget -O chromedriver_linux64.zip "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}"
          unzip chromedriver_linux64.zip
          export PATH=$PATH:$PWD
          cd..

      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      
      - name: Print Selenium version
        run: python -c "import selenium; print(selenium.__version__)"

      - name: Print Chromium version
        run: chromium-browser --version


      - name: Print Chromedriver version
        run: chromedriver --version

      - name: Run tests
        working-directory: task1
        run: python -m behave --verbose || true
      
      - name: Enable Chromedriver verbose logging
        run: |
          echo "CHROME_LOG_FILE=chrome.log" >> $GITHUB_WORKSPACE/.env

      - name: Upload log file as artifact
        uses: actions/upload-artifact@v2
        with:
          name: chromedriver-log
          path: chrome.log
