name: Behave tests in Docker

on:
  schedule:
    - cron: "30 9 * * 2,5"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.9

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install behave
        run: pip install behave

      - name: Install selenium
        run: pip install selenium
      
      - name: Install Webdriver Manager
        run: pip install webdriver_manager
      
      - name: Install Chromium
        run: |
          apt-get update
          apt-get install -y sudo wget
          sudo apt-get install -y chromium-browser
          export CHROMIUM_PATH=$(which chromium-browser)

      
      - name: Print Chromium version
        run: chromium-browser --version

      - name: Install Chromedriver
        run: |
          cd drivers
          wget -O chromedriver_linux64.zip "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}"
          unzip chromedriver_linux64.zip
          export PATH=$PATH:$PWD
          cd..



      
      - name: Print Selenium version
        run: python -c "import selenium; print(selenium.__version__)"




      - name: Print Chromedriver version
        run: chromedriver --version

      - name: Run tests
        working-directory: task1
        run: python -m behave --verbose || true
      
      - name: Enable Chromedriver verbose logging
        run: |
          echo "CHROME_LOG_FILE=chrome.log" >> $GITHUB_WORKSPACE/.env

      - name: Upload log file as artifact
        uses: actions/upload-artifact@v2
        with:
          name: chromedriver-log
          path: chrome.log
