name: Behave tests in Docker

on:
  schedule:
    - cron: "30 9 * * 2,5"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.9
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install behave
        run: pip install behave

      - name: Install selenium
        run: pip install selenium

      - name: Install Firefox
        run: |
          apt-get update
          apt-get install -y sudo wget
          sudo apt-get install -y libdbus-glib-1-2 libxt6 libsm6 libxrender1 libfontconfig1 libasound2 libgtk-3-0 libxcb1
          wget -O firefox.tar.bz2 "https://download.mozilla.org/?product=firefox-latest-ssl&os=linux64&lang=en-US"
          sudo tar xjf firefox.tar.bz2 -C /opt/
          sudo ln -s /opt/firefox/firefox /usr/bin/firefox
          export FIREFOX_PATH=$(which firefox)

      - name: Print Selenium version
        run: python -c "import selenium; print(selenium.__version__)"

      - name: Print Firefox version
        run: firefox --version

      - name: Run tests
        working-directory: task1
        run: python -m behave
