name: Behave tests in Docker

on:
  schedule:
    - cron: "30 9 * * 2,5"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.9
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install behave
        run: pip install behave

      - name: Install selenium
        run: pip install selenium

      - name: Install Firefox
        run: |
          sudo apt-get update && sudo apt-get install -y firefox
          export FIREFOX_PATH=$(which firefox)
          export PATH=$PATH:/usr/lib/firefox/

      - name: Run tests
        working-directory: task1
        run: python -m behave
