name: Behave tests in Docker

on:
  schedule:
    - cron: "30 9 * * 2,5"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.9
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install behave
        run: pip install behave

      - name: Install selenium
        run: pip install selenium
      
      - name: Install Webdriver Manager
        run: pip install webdriver_manager

      - name: Where the fuck are we?
        run: |
          ls
          cd drivers 
          ls
          cd

      - name: Install geckodriver
        run: |
          cd drivers
          wget https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz
          tar -xvzf geckodriver-v0.33.0-linux64.tar.gz
          export PATH=$PATH:$PWD
          echo 'export PATH=$PATH:$PWD' >> $HOME/.bashrc

      - name: Install Firefox
        run: |
          apt-get update
          apt-get install -y sudo wget
          sudo apt-get install -y libdbus-glib-1-2 libxt6 libsm6 libxrender1 libfontconfig1 libasound2 libgtk-3-0 libxcb1 libx11-xcb1
          wget -O firefox.tar.bz2 "https://download.mozilla.org/?product=firefox-latest-ssl&os=linux64&lang=en-US"
          sudo tar xjf firefox.tar.bz2 -C /opt/
          sudo ln -s /opt/firefox/firefox /usr/bin/firefox
          export FIREFOX_PATH=$(which firefox)

      - name: Create non-root user
        run: |
          sudo useradd -m myuser
          echo "myuser ALL=(ALL) NOPASSWD: ALL" | sudo tee -a /etc/sudoers
          sudo su myuser

      - name: Print Selenium version
        run: python -c "import selenium; print(selenium.__version__)"

      - name: Print Firefox version
        run: sudo -u myuser firefox --version

      - name: Print Geckodriver version
        run: |
          cd drivers
          ls -l
          export PATH=$PATH:$PWD
          ./geckodriver --version
          cd

      - name: Run tests
        working-directory: task1
        run: python -m behave --verbose
